[package]
name = "pktspec"
authors = ["Nathaniel Bennett <me[at]nathanielbennett[dotcom]>"]
rust-version = "1.65"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
